import type {User} from './auth';
import type {Template} from './template';
import type {Campaign} from './campaign';

export type RootStackParamList = {
  Splash: undefined;
  Login: undefined;
  Register: undefined;
  Main: undefined;
  Dashboard: {user?: User};
  Campaigns: undefined;
  CampaignDetails: {campaignId: string};
  CreateCampaign: {edit?: Campaign; duplicate?: Campaign} | undefined;
  Inbox: undefined;
  Conversation: {conversationId: string};
  Search: undefined;
  SavedReplies: undefined;
  Templates: undefined;
  CreateTemplate: {templateToEdit?: Template} | undefined;
  TemplateDetails: {templateId: string};
  Analytics: undefined;
  WelcomeMessageSettings: undefined;
  ContactChangeAlerts: undefined;
  ContactHistory: {phoneNumber: string};
  MessageErrors: undefined;
  TemplateAnalytics: undefined;
  OptInManager: undefined;
  BusinessLocationEditor: undefined;
  ViewOnceMediaComposer: {phoneNumber: string; conversationId?: string};
  StatusComposer: undefined;
  StatusList: undefined;
  RoleManager: undefined;
  PermissionEditor: {role: any};
  GroupMessage: undefined;
  FlowList: undefined;
  FlowBuilder: {flowId?: string} | undefined;
  FlowDetails: {flowId: string};
  SendFlow: {flow: any};
  Channels: undefined;
  ChannelMessages: {channelId: string};
  ChannelAnalytics: {channelId: string};
  CreateChannel: undefined;
  AuditLogs: undefined;
  Privacy: undefined;
};
